version: "3.1"
services:
  github_responder:
    ports:
      - 4567:4567
    image: alexellis2/github-secret-integration
    secrets:
        - github_webhook

secrets:
  github_webhook:
    file: ./github_webhook.secret 
